name: Effy Wild
favicon: null
layout_spectrum: 0.6349628842435777
typography_spectrum: 0.5104975064750761
title: A Filing Cabinet of Personal Delights
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefeb3'
    - '#170909'
    - '#c2c2c2'
    - '#899b8f'
    - '#9f1d63'
  brandStrength: 0.8125
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.5413934108801186
purpose: []
